apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../default
images:
- name: akskubeflow.azurecr.io/kubeflownotebookswg/notebook-controller
  newName: akskubeflow.azurecr.io/kubeflownotebookswg/notebook-controller
  newTag: v1.7.0
